# Generated by Django 4.2.23 on 2025-10-23 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meusite', '0002_endereco_remove_pessoa_bairro_pessoa_usuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='cargo',
            field=models.CharField(choices=[('comum', 'Comum'), ('gerente', 'Gerente'), ('admin', 'Administrador')], default='comum', max_length=20),
        ),
    ]
